export * from "./insertion/insertion"
export * from "./selection/selection"
export * from "./shell/shell"
export * from "./merge/merge"
export * from "./quick/quick"
export * as Heap from "./heap/heap"