export * from "./Insertion/Insertion"
export * from "./Selection/Selection"
export * from "./Shell/Shell"
export * from "./Merge/Merge"
export * from "./Quick/Quick"
export * as Heap from "./Heap/Heap"